version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # region Listeners configuration
      # With the following configuration, Kafka will be accesible:
      # * To the Docker containers inside the VM through `kafka:29092`
      # * To the VM and the host machine through `localhost:9092`
      KAFKA_LISTENERS: INSIDE://kafka:29092,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # endregion
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Create topics:
      # * exampletopic: 3 partitions, 1 replicas
      KAFKA_CREATE_TOPICS: "exampletopic:3:1"
      # Create topics automatically
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
