#version: '2'
#services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      # Create 2 topics:
#      # * topic1: 1 partition, 1 replica
#      # * topic2: 1 partition, 1 replica
#      KAFKA_CREATE_TOPICS: "topic1:1:1,topic2:1:1"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
